# Generated by Django 6.0.6 on 2026-06-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_erp', '0002_auto_20260606_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фотография товара'),
        ),
    ]
