# Generated by Django 6.0.6 on 2026-06-09 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_erp', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает выдачи'), ('DELIVERED', 'Выдан сотруднику')], default='PENDING', max_length=15, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_erp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ мерча',
                'verbose_name_plural': 'Заказы мерча',
                'ordering': ['-created_at'],
            },
        ),
    ]
