# Generated by Django 6.0.6 on 2026-06-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_erp', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Оплачен (Собирается)'), ('READY', 'Ожидает получения (В офисе)'), ('DELIVERED', 'Выдан сотруднику')], default='PAID', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
